apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-sbph
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0041-tenant/tkrw-pr712-0075-0041-app/devfile-sample-sbph@sha256:9f2657dd7592ad22798fbb5459e396169bc4d422bce34d47a03e9a8e52622c24
        name: my-nodejs
        resources: {}
status: {}
